project:
  type: website
  output-dir: docs

website:
  title: "MODEVAIIA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - P1.qmd
      - P2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

